### ISSUE TITLE
Remove repeated tab code

### ISSUE THREAD

**Issue by sreehari2003** [DarkPhoenix2704/fossfolio#146]
https://github.com/DarkPhoenix2704/fossfolio/blob/63c405bd2714238d2ff61f51d2c50d155e988c14/apps/web/ui/components/ui/tabs.tsx#L1

@DarkPhoenix2704  this tab is already available in the "/ui/" folder all. shadcn files are added to that dir , in component.json it not updated can you remove this code and use the already existing code.

**Comment by sreehari2003** [comment]
Also new  changs is breaking the frontend

try going to https://www.fossfolio.com/events/DevHack.

**Comment by DarkPhoenix2704** [comment]
That was broken before my push

**Comment by DarkPhoenix2704** [comment]
WIll fix them
