### ISSUE TITLE
Mobile responsive

### ISSUE THREAD

**Issue by sreehari2003** [DarkPhoenix2704/fossfolio#27]
Most of the site is not mobile responsive yet we need to fix it we use chakra ui

**Comment by sra1kumar-NULL** [comment]
Can I work on this responsive issue ,could you assign me this issue ?

**Comment by DarkPhoenix2704** [comment]
Yeah Sure..

**Comment by sra1kumar-NULL** [comment]
> 

I feel like isn't any responsiveness issue cause iphone SE is the smallest width phone and homepage is not breaking in that device so.

**Comment by sreehari2003** [comment]
> > 
> 
> I feel like isn't any responsiveness issue cause iphone SE is the smallest width phone and homepage is not breaking in that device so. But if you want I can tweak the code a little to make sure it will not break what so ever.

instead a cloning main brnach try dev branch our code is very diffrent on our dev brnach currenlty we are creating pr towards dev branch until we can do a initial beta relese
