### ISSUE TITLE
Page shakes up in initial page load

### ISSUE THREAD

**Issue by sreehari2003** [DarkPhoenix2704/fossfolio#28]
Idk y but pages are causing a shanke in initial page load need help

**Comment by sra1kumar-NULL** [comment]
I've haven't faced this type of shake issues . Is it fixed ?

**Comment by DarkPhoenix2704** [comment]
@sreehari2003

**Comment by sreehari2003** [comment]
> I've haven't faced this type of shake issues . Is it fixed ?

try dev branch
