### ISSUE TITLE
Missing payload object? 

### ISSUE THREAD

**Issue by sreehari2003** [DarkPhoenix2704/fossfolio#46]
https://github.com/DarkPhoenix2704/fossfolio/blob/7dc4efba9c06229258805670525748bc62165302/apps/web/slices/auth/index.ts#L38

@AshminJayson  dispatch should have a payload object instead of parameters right?

**Comment by AshminJayson** [comment]
I tested both the current method and also `dispatch(authSlice.actions.setLoggedIn({ payload: data.user?.user_metadata }))`, and both seem to work the same, so should we make that change?
