### ISSUE TITLE
do we really need faker js ? its a bit large dependency !

### ISSUE THREAD

**Issue by sreehari2003** [DarkPhoenix2704/fossfolio#65]
https://github.com/DarkPhoenix2704/fossfolio/blob/5a5fd26158c191d22d9cfc8ac1cfe822bbc105f8/apps/api/src/user/user.service.ts#L7C30-L7C30

**Comment by DarkPhoenix2704** [comment]
Time being, for autogenerating, slug we can use it. Will migrate to other api or package later
